# Generated by Django 5.2.8 on 2025-11-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_alter_listing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
