# Generated by Django 5.2.8 on 2025-11-27 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0002_alter_conversation_created_by_and_more"),
        ("listings", "0007_alter_listing_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "notification_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("MESSAGE", "Message"),
                            ("LISTING_SOLD", "Listing Sold"),
                            ("NEW_OFFER", "New Offer"),
                            ("OFFER_ACCEPTED", "Offer Accepted"),
                            ("OFFER_DECLINED", "Offer Declined"),
                            ("LISTING_EXPIRED", "Listing Expired"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.listing",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.message",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient"], name="notificatio_recipie_1dd18d_idx"
                    ),
                    models.Index(
                        fields=["actor"], name="notificatio_actor_i_e2a3f1_idx"
                    ),
                ],
            },
        ),
    ]
