# Generated by Django 5.2.8 on 2025-12-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="proposed_by",
            field=models.CharField(
                blank=True,
                choices=[("buyer", "Buyer"), ("seller", "Seller")],
                max_length=10,
                null=True,
            ),
        ),
    ]
