# Generated by Django 5.2.8 on 2025-12-09 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_review"),
        ("transactions", "0002_transaction_proposed_by"),
    ]

    operations = []
